#!/usr/bin/env python3
"""Generate the compact Q14 polyphase FIR table used by mixer.c."""

from math import cos, pi, sin
from pathlib import Path

TAPS = 24
PHASES = 160
STORED_PHASES = PHASES // 2 + 1
SHIFT = 14
SCALE = 1 << SHIFT
LEFT = TAPS // 2 - 1


def coefficient_row(phase: int) -> list[int]:
    fraction = phase / PHASES
    coefficients = []

    for tap in range(TAPS):
        distance = fraction - (tap - LEFT)
        if distance == 0.0:
            sinc = 1.0
        else:
            sinc = sin(pi * distance) / (pi * distance)
        position = distance / (TAPS / 2)
        if abs(position) >= 1.0:
            window = 0.0
        else:
            window = (0.42 + 0.5 * cos(pi * position) +
                      0.08 * cos(2.0 * pi * position))
        coefficients.append(sinc * window)

    total = sum(coefficients)
    quantized = [round(value * SCALE / total) for value in coefficients]
    center = min(range(TAPS),
                 key=lambda tap: abs(fraction - (tap - LEFT)))
    quantized[center] += SCALE - sum(quantized)
    return quantized


def generate() -> str:
    rows = [coefficient_row(phase) for phase in range(STORED_PHASES)]
    maximum_l1 = max(sum(abs(value) for value in row) for row in rows)
    assert all(sum(row) == SCALE for row in rows)
    assert maximum_l1 * 32768 < 1 << 31
    lines = [
        "/* Generated by tools/generate_resampler_coeffs.py. Do not edit. */",
        "#ifndef UAC_PSTV_RESAMPLER_COEFFS_H",
        "#define UAC_PSTV_RESAMPLER_COEFFS_H",
        "",
        f"#define UAC_RESAMPLER_TAPS {TAPS}",
        f"#define UAC_RESAMPLER_PHASES {PHASES}",
        f"#define UAC_RESAMPLER_STORED_PHASES {STORED_PHASES}",
        f"#define UAC_RESAMPLER_SHIFT {SHIFT}",
        f"#define UAC_RESAMPLER_LEFT {LEFT}",
        f"#define UAC_RESAMPLER_RIGHT {TAPS - LEFT - 1}",
        "#define UAC_RESAMPLER_HISTORY 32",
        "",
        f"/* Maximum Q14 coefficient L1 norm: {maximum_l1}. */",
        "static const int16_t uac_resampler_coefficients",
        "[UAC_RESAMPLER_STORED_PHASES][UAC_RESAMPLER_TAPS]",
        "\t__attribute__((aligned(64))) = {",
    ]
    for row in rows:
        lines.append("\t{ " + ", ".join(f"{value:6d}" for value in row) + " },")
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    destination = root / "src" / "resampler_coeffs.h"
    destination.write_text(generate(), encoding="ascii", newline="\n")
    print(destination)
